### PR TITLE
Fixed and added small code syntaxes for v5/index.ts, edited readme.md

### PR DESCRIPTION
**Pull request by t404owo**
v5/index.ts:
(wip: add JSDocs syntaxes)
added ";" for codes (because syntax)

readme.md:
code samples syntaxes fixed.
edited "user-agent" to "authorization".
added "old API version case" so the user knows how to when to user User-Agent and when Authorization.

### CODE REVIEW

**Comment by t404owo** [comment]
Please add JSDocs definitions and fix mine if possible, I'm still stucking at the "usercode" and "user", thx :D

**Comment by t404owo** [comment]
Also please add the first commit, because that's about readme

Else you can remove the rest, the last one please keep if possible because that's where ";" are added correctly.

**Review by bsdayo — APPROVED** [review]
Thanks!

**Comment by bsdayo** [comment]
> Please add JSDocs definitions and fix mine if possible, I'm still stucking at the "usercode" and "user", thx :D

`usercode` is the exact 9-digit code of each arc account, and `user` means "username" for AUA fuzzy searching.

I'll check it and thanks :D

**Comment by bsdayo** [comment]
Nothing bad, I'll merge it and publish a new version on npm.
...and by the way, add `;` to the line end or not is nearly the same (except for some special situations), and for me I prefer not... Just a flavor :D

**Pull request merged**
